name: Check Release Stability

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_stability:
    timeout-minutes: 30
    # environment: test-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
        # declare .env variables here
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MODE: ${{ secrets.MODE }}
          ORIGIN: ${{ secrets.ORIGIN }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - name: Check Formatting
        run: pnpm fmt
      - name: Run Linters
        run: pnpm lint
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Test Codebase
        run: pnpm test
        # declare .env variables here
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MODE: ${{ secrets.MODE }}
          ORIGIN: ${{ secrets.ORIGIN }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          IT_EMAIL: ${{ secrets.IT_EMAIL }}
          IT_PASS: ${{ secrets.IT_PASS }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
          DUMMY_EMAIL: ${{ secrets.DUMMY_EMAIL }}
          DUMMY_EMAIL1: ${{ secrets.DUMMY_EMAIL1 }}
          DUMMY_EMAIL2: ${{ secrets.DUMMY_EMAIL2 }}
          DUMMY_PASS: ${{ secrets.DUMMY_PASS }}
      - name: Upload Test Results
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: |
            playwright-results/
            vitest-results/
          retention-days: 90
          include-hidden-files: true
